Make sure you have 

```
DB_HOST=localhost
```

defined before starting manage.py!!
